name: Build Flutter APK

permissions:
  contents: read
  actions: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'    # pin to a specific SDK release

      - name: Install dependencies
        run: flutter pub get

      - name: Print Flutter version & doctor
        run: |
          flutter --version
          flutter doctor -v

      - name: List output directory
        run: ls -R build/app/outputs/

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
